version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'peopledb'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script
      - mysql_data:/var/lib/mysql

  nodejs:
    build: ./nodejs
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: peopledb

  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - nodejs
volumes:
  mysql_data:
